### ISSUE TITLE
Something wrong with interpolation?

### ISSUE THREAD

**Issue by magnargj** [zzyztyy/pyIGRF#2]
When plotting secular variation (only between 1995 and 2015), there seems to be a jump in values from the year 2 to 3 after the year of coefficients. Things fall back to "normal" every five years. I suspect this must be related to some rounding error?
![caspian-igrf_d](https://user-images.githubusercontent.com/5923183/50775404-61fee580-1296-11e9-821b-44411105fcd8.png)

**Comment by zzyztyy** [comment]
Thanks for you found my mistakes. You are right. Now the bug has been fixed.
This package should be checked more carefully. I will do it soon.
