### ISSUE TITLE
Has this code ever been cross-validated?

### ISSUE THREAD

**Issue by s-m-e** [zzyztyy/pyIGRF#3]
... against, for instance, [igrf12](https://github.com/scivision/igrf12) or the plain official [Fortran](https://www.ngdc.noaa.gov/IAGA/vmod/igrf12.f)/C implementations of the IGRF?

(As far as I can tell, this repository would be the first working pure Python implementation of this model that I have seen. Very fascinating, good work. EDIT: Not the first (?): [navtools](http://slott56.github.io/navtools/igrf11.html#igrf11.__call__))

**Comment by s-m-e** [comment]
Closed without a comment / reply?

**Comment by zzyztyy** [comment]
Sorry，it has not been cross-validated. You can find a official Python version[ in this web](https://www.ngdc.noaa.gov/IAGA/vmod/igrf.html).
