### ISSUE TITLE
igrf13coeffs.txt not included when installing using PyPI

### ISSUE THREAD

**Issue by mattkjames7** [zzyztyy/pyIGRF#6]
Hi, 
When importing the package after installing using pip3 it complains that the coefficient file is missing. It's quite an easy fix - just need to include it in the MANIFEST.in file before building the package.
Thanks for the IGRF module though - works a treat!
Cheers,
Matt.

**Comment by jordan-heemskerk** [comment]
Hey @mattkjames7 I believe this is fixed in version 0.3.1 (which looks like it got released today)

**Comment by mattkjames7** [comment]
Great news, thanks for the fix!
