### ISSUE TITLE
Incorrect calculations for 2020.0 and onward

### ISSUE THREAD

**Issue by proway2** [zzyztyy/pyIGRF#7]
Calculations with the latest IGRF 13 model are incorrect. They are very different with IGRF reference implementation. For example: lat 60.0, lon 40.0, alt 0.0, date 2020.13. The results are almost 0.8 degree different. And there is a huge leap between 2019.98 and 2020.0, which is impossible.

**Comment by eehongliang** [comment]
The index to use in igrf13coeffs interpolation for year 2020 is wrong. Need to fix it in the file "loadCoeffs.py", i.e. change the line below "pointer for last coefficient in pen-ultimate set of MF coefficients..." to "ll = 3255"

**Comment by proway2** [comment]
@eehongliang tried you solution, works well for me, but there are no unittests in this project. Who knows what else could be wrong?
Anyway, would you make a PR?
This line looks strange: https://github.com/zzyztyy/pyIGRF/blob/35e9b3deb7b264940fa713256863e72013169f42/pyIGRF/loadCoeffs.py#L50
Can not find such a thing in reference C implementaion.

**Comment by zzyztyy** [comment]
This project is directly recompiled from Fortran code. The magic number like "ll=3255" is everywhere. The var "ll" represent the positions of first g10. So adding 199 to "ll" means using the next row i.e. 2020. It is the solution to fix this error.
